---
- name: update hosts
  hosts: all
  gather_facts: false


  tasks:
    - name: Search and download Windows updates
      win_updates:
        category_names:
          - Application
          - CriticalUpdates
          - DefinitionUpdates
          - SecurityUpdates
          - Updates
        log_path: c:\tmp\update.log
        reboot: yes
        reboot_timeout: 120
#       server_selection: Point to WSUS server