- name: Run Updates on Terminal Servers then wait 7 mins
  hosts: all
  gather_facts: yes
  connection: winrm

  tasks:
  - name: Window updates
    win_updates:
      category_names:
        - Application
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
    reboot: yes
    reboot_timeout: 420
    log_path: c:\tmp\updatelogs\