---
- name: update hosts
  hosts: all
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Search and download Windows updates without installing
      win_updates:
        category_names:
          - Application
          - CriticalUpdates
          - DefinitionUpdates
          - SecurityUpdates
          - Updates
        log_path: c:\tmp\update.log